---

name: release
run-name: release-${{ github.ref_name }}
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Set to true to create an archive instead of a release"
        type: boolean
        required: false
        default: false
  release:
    types:
      - published

env:
  gap-branch: stable-4.14

jobs:
  assets-build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: git -- checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}

      - uses: gap-actions/setup-gap@v2
        with:
          GAPBRANCH: ${{ env.gap-branch }}
          GAP_PKGS_TO_BUILD: json

      - name: gap -- build docs
        uses: gap-actions/build-pkg-docs@v1
        with:
          use-latex: 'true'

      - name: gap -- release package
        uses: gap-actions/release-pkg@v1
        with:
          dry-run: ${{ inputs.dry-run }}
